using System;
namespace System.Net.Sockets
{
    public enum SocketError
    {
        Success,
        SocketError = -1,
        Interrupted = 10004,
        AccessDenied = 10013,
        Fault,
        InvalidArgument = 10022,
        TooManyOpenSockets = 10024,
        WouldBlock = 10035,
        InProgress,
        AlreadyInProgress,
        NotSocket,
        DestinationAddressRequired,
        MessageSize,
        ProtocolType,
        ProtocolOption,
        ProtocolNotSupported,
        SocketNotSupported,
        OperationNotSupported,
        ProtocolFamilyNotSupported,
        AddressFamilyNotSupported,
        AddressAlreadyInUse,
        AddressNotAvailable,
        NetworkDown,
        NetworkUnreachable,
        NetworkReset,
        ConnectionAborted,
        ConnectionReset,
        NoBufferSpaceAvailable,
        IsConnected,
        NotConnected,
        Shutdown,
        TimedOut = 10060,
        ConnectionRefused,
        HostDown = 10064,
        HostUnreachable,
        ProcessLimit = 10067,
        SystemNotReady = 10091,
        VersionNotSupported,
        NotInitialized,
        Disconnecting = 10101,
        TypeNotFound = 10109,
        HostNotFound = 11001,
        TryAgain,
        NoRecovery,
        NoData,
        IOPending = 997,
        OperationAborted = 995
    }
}
